### PR TITLE
Update project to use Nuget packages and clean up some processes

### PR DESCRIPTION
**Pull request by Local9**
Refactoring project;

- [x] - Use Nuget CFX Packages
- [x] - Use NewtonSoft 12.0.2 Nuget
- [x] - Refactor server command so ACE Permission can be used
- [x] - Set Maximum Jail Time to be configurable via Resource Metadata
- [x] - Refactor client to remove non-required events
- [x] - Add configuration options for positions
- [x] - Remove references to CDN in HTML

### CODE REVIEW

**Comment by fixterjake** [comment]
Surprised people still use this, but hey, this all looks good, feel free to tag me when you get it complete and I'll merge it in.

**Comment by Local9** [comment]
I was asked by someone to take a look at it, I've gone... a bit overboard with it all o.O

**Comment by fixterjake** [comment]
Yeah this is all great, I've come a long way since I wrote this so I'm sure a ton was pretty bad. And lots of DOJ references.

**Comment by Local9** [comment]
I'm staying away from adding in additional systems (like adding fxEvents because I love fxEvents https://github.com/manups4e/FxEvents) but will be looking into something to deal with OneSync servers (player list feature for Jail NUI) if I can without adding fxEvents, just so used to using fxEvents 😳

There were a lot of DOJ references so I've been chipping away at each of them, and still need to remove the CDN links to libraries and add them directly where required, will pick that up tomorrow. Updated projects to a newer style and so on, still having a fight with NewtonSoft 12.0.2 for some reason but I'll tackle that later, I'd rather use the Nuget over a dependancy dll in the repo.

Let me know if there is anything else.

**Comment by fixterjake** [comment]
I haven't done FiveM development since this point, so really not too sure how the ecosystem has changed since then.

**Comment by Local9** [comment]
Ah, no worries, in a few months it'll be changing again when they release the new C# libraries, thorium has been doing some amazing work on that side. Performance will be 10x better.

**Comment by fixterjake** [comment]
Huh that's neat, have thought about getting back into it, but am not in any communities now so no where to throw my time at.

**Comment by Local9** [comment]
More than welcome to join the community linked below, we mostly do things for ourselves but we do join in with sharing and helping others.

FiveM C# & ScaleformUI dedicated discord: https://discord.gg/KKN7kRT2vM

**Comment by Local9** [comment]
Finally remembered with the `.json` config was having issues loading on the client and have updated the project to use the Nuget Packages so there is no longer a requirement for a dependancies folder.

**Comment by Local9** [comment]
@fixterjake good to review now various issues looked into and dealt with, should open up for more features.

**Comment by fixterjake** [comment]
Looks good, thanks for the contribution

**Pull request merged**
